# Generated by Django 5.0.6 on 2024-06-04 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_tempuser_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempUser',
        ),
    ]
